[project]
name = 'upcat_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.candidate_images]
path = 'contracts/candidate_images.clar'
clarity_version = 2
epoch = 2.5

[contracts.file_indexing]
path = 'contracts/file_indexing.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_payment_splitting]
path = 'contracts/multi_send_with_payment_splitting.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5

[contracts.shed_with_conditional_setter]
path = 'contracts/shed_with_conditional_setter.clar'
clarity_version = 2
epoch = 2.5

[contracts.voters_candidate_images]
path = 'contracts/voters_candidate_images.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
